contentColumnType: string
fieldGroup: 4a11776f-b873-4c45-9544-1db02f716c35
handle: logo
instructions: ''
name: Logo
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:bd9723db-ef0d-4446-95de-c50a99e7b7e1'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:bd9723db-ef0d-4446-95de-c50a99e7b7e1'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:bd9723db-ef0d-4446-95de-c50a99e7b7e1'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
