enableVersioning: true
handle: categoryPage
name: 'Category page'
propagationMethod: all
siteSettings:
  cd3a021e-1aa2-4de7-8d78-153118c9aa41:
    enabledByDefault: true
    hasUrls: true
    template: pages\categoryPage
    uriFormat: 'category-page/{slug}'
type: channel
