enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  cd3a021e-1aa2-4de7-8d78-153118c9aa41:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
