enableVersioning: true
handle: socialNetworks
name: 'Social networks'
propagationMethod: all
siteSettings:
  cd3a021e-1aa2-4de7-8d78-153118c9aa41:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'social-networks/{slug}'
type: channel
